name: morre_flutter
description: MORRE currency tracker Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  firebase_messaging: ^16.6.0
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.5
  flutter_local_notifications: ^22.3.0
  fl_chart: ^1.2.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
